Repository Team-BodyBuddy/body-buddy-front, pull requests merged in 2025-02, with the labels that each got.

#84 [api] axiosInstance 초기 세팅
  .gitignore
  package-lock.json
  package.json
  src/apis/axiosInstance.js
Labels: 🔗 api

#87 Setting: App
  package-lock.json
  package.json
  src/styles/GlobalStyles.ts
Labels: ⚠️ warning

#83 [design] Calendar Date 높이 수정
  src/components/Calendar/CalendarElement/Date/Styles.ts
  src/components/Calendar/CalendarElement/Header/Styles.ts
  src/components/Calendar/Styles.ts
Labels: 💄 design

#65 [chore] rem으로 단위 변환, 컴포넌트 일부 수정
  src/assets/icons/checkMark-circle-blue.svg
  src/assets/icons/checkMark-circle-green.svg
  src/components/SignUpPage/AuthInput/AuthInput.tsx
  src/components/SignUpPage/CheckButton/CheckButton.tsx
  src/components/SignUpPage/NicknameInput/NicknameInput.tsx
  src/components/SignUpPage/PageLink/PageLink.tsx
  src/components/SignUpPage/PageLink/Styles.ts
  src/components/SignUpPage/PasswordInput/PasswordInput.tsx
  src/components/SignUpPage/UserInfoInput/UserInfoInput.tsx
  src/components/icons.ts
  src/pages/Login_Signup/FindIdPage/FindIdPage.tsx
  src/pages/Login_Signup/FindIdPage/Styles.ts
  src/pages/Login_Signup/FindPasswordPage/FindPasswordPage.tsx
  src/pages/Login_Signup/FindPasswordPage/Styles.ts
  src/pages/Login_Signup/LoadingPage/Styles.ts
  src/pages/Login_Signup/LoginPage/LoginPage.tsx
  src/pages/Login_Signup/LoginPage/Styles.ts
  src/pages/Login_Signup/UserSignUpPage/Styles.ts
  src/pages/Login_Signup/UserSignUpPage/UserSignUpPage.tsx
  src/pages/Trainer/TrainerSignUpPage/Styles.ts
  src/pages/Trainer/TrainerSignUpPage/TrainerSignUpPage.tsx
Labels: 🖤 refactoring

#89 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: 📜 docs

#92 [feat] Feat: Main-Avatar apis
  src/apis/avatar/index.ts
  src/apis/avatar/mocks.ts
  src/apis/avatar/types.ts
  src/assets/icons/BodyBuddyChar.svg
  src/components/DefaultContent/DefaultContent.tsx
  src/components/HeaderControls/HeaderControls.tsx
  src/components/PopatoSection/PotatoSection.tsx
  src/components/TrendGraph/Styles.ts
  src/components/TrendGraph/TrendGraph.tsx
  src/components/icons.ts
  src/pages/Trainer/TrainerMemberPage/TrainerMemberPage.tsx
  src/pages/User/UserPage/Styles.ts
  src/pages/User/UserPage/UserPage.tsx
  src/react-query/query/useAvatarQuery.tsx
  src/zustand/stores/FluxContext.tsx
  src/zustand/stores/initialState.ts
Labels: 🔗 api
