Repository Team-BodyBuddy/body-buddy-front, pull requests merged in 2025-01, with the labels that each got.

#23 Design/user login signup
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/BODY BUDDY.svg
  src/assets/icons/arrowLeft.svg
  src/assets/icons/checkMark-circle-gray.svg
  src/assets/icons/checkMark-circle-green.svg
  src/assets/icons/line.svg
  src/assets/icons/select.svg
  src/assets/icons/titleGroup.svg
  src/components/icons.ts
  src/pages/FindIdPage/FindIdPage.tsx
  src/pages/FindIdPage/Styles.ts
  src/pages/FindPasswordPage/FindPasswordPage.tsx
  src/pages/FindPasswordPage/Styles.ts
  src/pages/LoadingPage/LodingPage.tsx
  src/pages/LoadingPage/Styles.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/Styles.ts
  src/pages/TrainerSignUpPage/Styles.ts
  src/pages/TrainerSignUpPage/TrainerSignUpPage.tsx
  src/pages/UserSignUpPage/Styles.ts
  src/pages/UserSignUpPage/UserSignUpPage.tsx
Labels: 💄design

#24 [Design/ranking] 랭킹 페이지 디자인
  package-lock.json
  package.json
  src/assets/icons/Green_health.svg
  src/assets/icons/default_profile.svg
  src/assets/icons/main_cart.svg
  src/components/icons.ts
  src/components/ranking/NoGymMessage.tsx
  src/components/ranking/Ranking.tsx
  src/components/ranking/RankingList.tsx
  src/mocks/rank-mock.ts
  src/pages/RankingPage/RankingPage.tsx
  src/pages/RankingPage/Styles.ts
  src/styles/color.ts
Labels: 💄design

#25 [Fix 빌드오류] fix: icons App 파일 오류 수정
  src/App.tsx
  src/components/icons.ts
Labels: ❗error

#28 Design/mypage
  src/pages/MyPage/Styles.ts
  src/pages/RankingPage/RankingPage.tsx
Labels: 💄design

#35 [warning]: unused import 정리
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarElement/Week/CalendarWeek.tsx
  src/components/Todo/TodoElement.tsx
Labels: ⚠️warning

#36 Design/trainer portfolio
  src/App.tsx
  src/components/EditForm/EditForm.tsx
  src/components/EditForm/Styles.ts
  src/components/EditableList/EditableList.tsx
  src/components/EditableList/Styles.ts
  src/pages/PortfolioPage/Styles.ts
  src/pages/TrainerPortfolio/Styles.ts
  src/pages/TrainerPortfolio/TrainerPortfolio.tsx
Labels: 💄design

#39 [Design] 트레이너 : 마이페이지
  src/assets/icons/ExitLogo.svg
  src/assets/icons/LogoutLogo.svg
  src/components/BackButton/Styles.ts
  src/components/EditInfo/EditInfo.tsx
  src/components/ExitPage/Exit/Exit.tsx
  src/components/ExitPage/Exit/Styles.ts
  src/components/ExitPage/Logout/Logout.tsx
  src/components/ExitPage/Logout/Styles.ts
  src/components/MyPage/Buttons/Buttons.tsx
  src/components/MyPage/Buttons/Styles.ts
  src/components/MyPage/EditInfo/EditInfo.tsx
  src/components/MyPage/EditInfo/Styles.ts
  src/components/MyPage/Nickname/Nickname.tsx
  src/components/MyPage/Nickname/Styles.ts
  src/components/MyPage/Toast/Styles.ts
  src/components/MyPage/Toast/Toast.tsx
  src/components/MyPage/UserInfo/Styles.ts
  src/components/MyPage/UserInfo/UserInfo.tsx
  src/components/icons.ts
  src/pages/ExitPage/ExitPage.tsx
  src/pages/ExitPage/Styles.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/TrainerMyPage/Styles.ts
  src/pages/TrainerMyPage/TrainerMyPage.tsx
Labels: 💄design

#41 [design] 랭킹페이지 랭킹리스트 상단 헤드 고정
  src/components/Ranking/Ranking.tsx
  src/components/Ranking/RankingList.tsx
  src/pages/RankingPage/RankingPage.tsx
  src/pages/RankingPage/Styles.ts
Labels: 💄 design

#43 [docs] Create PR_TEMPLATE.md
  .github/PUL_REQUEST_TEMPLATE/PR_TEMPLATE.md
Labels: 📜 docs

#50 [Design] 트레이너 : 마이페이지
  src/App.tsx
  src/components/DefaultContent/DefaultContent.tsx
  src/components/Modal/PointModal/PointModal.tsx
  src/components/Modal/PointModal/Styles.ts
  src/components/Modal/TrainerRequestModal/Styles.ts
  src/components/Modal/TrainerRequestModal/TrainerRequestModal.tsx
  src/pages/TrainerMyPage/Styles.ts
  src/pages/TrainerMyPage/TrainerMyPage.tsx
Labels: 💄 design

#48 [docs] Update issue templates
  .github/ISSUE_TEMPLATE/issue_feature.md
Labels: 📜 docs

#63 [design] calendar 수정
  src/assets/icons/calendar-select.svg
  src/assets/icons/calendar.svg
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Styles.ts
  src/components/Modal/GraphModal/GraphModal.tsx
  src/components/Modal/GraphModal/Styles.ts
  src/components/icons.ts
Labels: 💄 design
